@startuml
'https://plantuml.com/sequence-diagram

autonumber

Mainframe Drop Equipment


Virologist->Equipment++:discard(Virologist)
Equipment->Equipment:removeEffect(Virologist)
Equipment-->Virologist--
@enduml