@startuml
'https://plantuml.com/sequence-diagram
autonumber

mainframe Steal Default

actor Player

Player -> RobberVirologist++: steal(Robber, TargetVirologist)
'így csak egy interface kell, lehet ez jobb is, mint különszedve (CD-n viszont még hagytam a kettőt))

RobberVirologist -> TargetVirologist++: handleSteal(Agent, Virologist, TargetVirologist)



alt deafult handleStealStrategy applied on TargetVirologist
    TargetVirologist -->RobberVirologist: null
else paralyzed handleStealStrategy applied on TargetVirologist

        note left TargetVirologist
            The player choose the wanted thing here
        end note

        TargetVirologist->Collectable++:discard()
        Collectable-->TargetVirologist--

    TargetVirologist -->RobberVirologist--: Collectable
    RobberVirologist->Collectable++:collectby(Robber)
    Collectable-->RobberVirologist--:
end

RobberVirologist --> Player --
@enduml