@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Attack Forget Agent Def

actor Player

Player -> "virologist: Virologist"++: useAgent(forget, targetVirologist)
"virologist: Virologist" -> TargetVirologist++: attack(forget, virologist, targetVirologist)
TargetVirologist -> Cloak++ : applyEffect(virologist: Virologist)

Cloak -> Cloak++ : getStrategy()
Cloak --> Cloak-- : defenseStrategy

Cloak -> TargetVirologist++: setDefenseStrategy(defensestrategy: DefenseStrategy)

TargetVirologist -> TargetVirologist++: defense(vitusDance: VitusDance, virologist: Virologist,  targetVirologist: Virologist)


note over TargetVirologist
    When the virologist have a cloak, there is
    an **82.3%** chance that the attack will **fail.**
end note

note right of TargetVirologist
Get a random number as a percentage.
end note

TargetVirologist -> TargetVirologist: surviveRate = generateRandomNumber()

opt if (surviveRate > 0.823)
    TargetVirologist -> VitusDance++: +applyEffect(targetVirologist: Virologist)

       VitusDance -> VitusDance++ : getStrategy()
       VitusDance --> VitusDance-- : moveStrategy

       VitusDance -> TargetVirologist++: setMoveStrategy(moveStrategy)
       TargetVirologist --> VitusDance--
       VitusDance --> TargetVirologist--
end opt

TargetVirologist --> TargetVirologist --

TargetVirologist --> Cloak --
Cloak --> TargetVirologist --


TargetVirologist --> Virologist --

Virologist --> Player --
@enduml