@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Attack Protection Agent

actor Player

Player -> "virologist: Virologist"++: useAgent(protection, targetVirologist)
"virologist: Virologist" -> "targetVirologist: TargetVirologist"++: attack(protection, virologist, targetVirologist)

"targetVirologist: TargetVirologist" -> "cloak: Cloak" ++ : applyEffect(targetVirologist)

"cloak: Cloak"  -> "cloak: Cloak" ++ : getStrategy()
"cloak: Cloak"  --> "cloak: Cloak" -- : defenseStrategy

"cloak: Cloak"  -> "targetVirologist: TargetVirologist"++: setDefenseStrategy(defensestrategy)

"targetVirologist: TargetVirologist" -> "protection: Protection"++ : applyEffect(targetVirologist)

    "protection: Protection" -> "protection: Protection"++ : getStrategy()
    "protection: Protection" --> "protection: Protection"-- : defenseStrategy

    "protection: Protection" -> "targetVirologist: TargetVirologist"++: setDefenseStrategy(defenseStrategy)
    "targetVirologist: TargetVirologist" --> "protection: Protection"--
 "protection: Protection" --> "targetVirologist: TargetVirologist"--

"targetVirologist: TargetVirologist" --> "cloak: Cloak"  --
"cloak: Cloak" --> "targetVirologist: TargetVirologist" --


"targetVirologist: TargetVirologist" --> "virologist: Virologist" --

"virologist: Virologist" --> Player --
@enduml