@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Attack Forget Agent

actor Player

Player -> "virologist: Virologist"++: useAgent(vitusDance, targetVirologist)
"virologist: Virologist" -> "targetVirologist: TargetVirologist"++: attack(vitusDance, virologist, targetVirologist)
"targetVirologist: TargetVirologist" -> "cloak: Cloak"++ : applyEffect(targetVirologist)

"cloak: Cloak" -> "cloak: Cloak"++ : getStrategy()
"cloak: Cloak" --> "cloak: Cloak"-- : defenseStrategy

"cloak: Cloak" -> "targetVirologist: TargetVirologist"++: setDefenseStrategy(defensestrategy)

"targetVirologist: TargetVirologist" -> "vitusDance: VitusDance"++ : applyEffect(targetVirologist)

   "vitusDance: VitusDance" -> "vitusDance: VitusDance"++ : getStrategy()
   "vitusDance: VitusDance" --> "vitusDance: VitusDance"-- : moveStrategy

   "vitusDance: VitusDance" -> "targetVirologist: TargetVirologist"++: setMoveStrategy(moveStrategy)
   "targetVirologist: TargetVirologist" --> "vitusDance: VitusDance"--

   "vitusDance: VitusDance" --> "targetVirologist: TargetVirologist"--


"targetVirologist: TargetVirologist" --> "cloak: Cloak" --
"cloak: Cloak" --> "targetVirologist: TargetVirologist" --


"targetVirologist: TargetVirologist" --> "virologist: Virologist" --

"virologist: Virologist" --> Player --
@enduml