@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Attack VitusDance Agent Back

actor Player

Player -> "virologist: Virologist"++: useAgent(vitusDance, targetVirologist)
"virologist: Virologist" -> "targetVirologist: TargetVirologist"++: attack(vitusDance, virologist, targetVirologist)
"targetVirologist: TargetVirologist" -> "cloak: Cloak"++ : applyEffect(targetVirologist)

"cloak: Cloak" -> "cloak: Cloak"++ : getStrategy()
"cloak: Cloak" --> "cloak: Cloak"-- : defenseStrategy

"cloak: Cloak" -> "targetVirologist: TargetVirologist"++: setDefenseStrategy(defensestrategy)

"targetVirologist: TargetVirologist" -> "targetVirologist: TargetVirologist"++: defense(vitusDance, virologist,  targetVirologist)

note over "targetVirologist: TargetVirologist"
    Gloves will attack back the attacker
    At implementation, we must make sure, **no infinite loop** occurs!
end note

"targetVirologist: TargetVirologist" -> "virologist: Virologist"++: attack(vitusDance,  targetVirologist, virologist)
"virologist: Virologist" -> "vitusDance: VitusDance"++ : applyEffect(virologist)

       "vitusDance: VitusDance" -> "vitusDance: VitusDance"++ : getStrategy()
       "vitusDance: VitusDance" --> "vitusDance: VitusDance"-- : moveStrategy

       "vitusDance: VitusDance" -> "virologist: Virologist"++: setMoveStrategy(moveStrategy)
       "virologist: Virologist" --> "vitusDance: VitusDance"--

       "vitusDance: VitusDance" --> "virologist: Virologist"--
"virologist: Virologist" --> "targetVirologist: TargetVirologist"--

"targetVirologist: TargetVirologist" --> "targetVirologist: TargetVirologist" --

"targetVirologist: TargetVirologist" --> "cloak: Cloak" --
"cloak: Cloak" --> "targetVirologist: TargetVirologist" --


"targetVirologist: TargetVirologist" --> "virologist: Virologist" --

"virologist: Virologist" --> Player --
@enduml