@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Attack Forget Agent Def

actor Player

Player -> "virologist: Virologist"++: useAgent(forget, targetVirologist)
"virologist: Virologist" -> TargetVirologist++: attack(forget, virologist, targetVirologist)
TargetVirologist -> Cloak++ : applyEffect(v: Virologist)

Cloak -> Cloak++ : getStrategy()
Cloak --> Cloak-- : defenseStrategy

Cloak -> TargetVirologist++: setDefenseStrategy(defensestrategy: DefenseStrategy)

TargetVirologist -> TargetVirologist++: defense(paralyzed: Paralyzed, virologist: Virologist,  targetVirologist: Virologist)


note over TargetVirologist
    If the virologist have this agent, he is invincible
end note

TargetVirologist --> TargetVirologist --

TargetVirologist --> Cloak --
Cloak --> TargetVirologist --


TargetVirologist --> Virologist --

Virologist --> Player --
@enduml