@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Collect Gencode

actor Player

Player -> "v:Virologist": collect()
Activate "v:Virologist"

"v:Virologist" -> "l:Lab": getCollectable()
Activate "l:Lab"
"l:Lab" -> "v:Virologist": <Gencode>
Deactivate "l:Lab"

"v:Virologist" -> "g:GenCode": collectBy(Virologist)
Activate "g:GenCode"

"g:GenCode" -> "v:Virologist"++:SetGencode()
"v:Virologist" -->"g:GenCode"--

"g:GenCode" --> "v:Virologist":
Deactivate "g:GenCode"
"v:Virologist" --> Player
Deactivate "v:Virologist"

@enduml