@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Collect Cloak

actor Player

Player -> "virologist: Virologist": collect()
Activate "virologist: Virologist"

"virologist: Virologist" -> "shelter:Shelter": getCollectable()
Activate "shelter:Shelter"
"shelter:Shelter" --> "virologist: Virologist": <Cloak>
Deactivate "shelter:Shelter"

"virologist: Virologist" -> "cloak:Cloak": collectBy(Virologist)
Activate "cloak:Cloak"

"cloak:Cloak" -> "cloak:Cloak"++ : applyEffect(virologist)

 "cloak:Cloak" -> "cloak:Cloak"++ : getStrategy()
 "cloak:Cloak" --> "cloak:Cloak"-- : defenseStrategy

 "cloak:Cloak" -> "virologist: Virologist"++: setDefenseStrategy(defenseStrategy)
"virologist: Virologist" --> "cloak:Cloak"--



"cloak:Cloak" --> "cloak:Cloak"--


"cloak:Cloak" --> "virologist: Virologist"--


"virologist: Virologist" --> Player
Deactivate "virologist: Virologist"

@enduml