@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Collect NukleicAcid

actor Player

Player -> "v:Virologist": collect()
Activate "v:Virologist"

"v:Virologist" -> "s:Storage": getCollectable()
Activate "s:Storage"
"s:Storage" -> "v:Virologist": <NukleicAcid>
'Ide sztem Matter illene jobban, csak hát az absztrakt...
Deactivate "s:Storage"

"v:Virologist" -> "n:NukleicAcid": collectBy(Virologist)
Activate "n:NukleicAcid"

"n:NukleicAcid" -> "v:Virologist" ++: SetNucleicAcid()
"v:Virologist"--> "n:NukleicAcid" --

"n:NukleicAcid" --> "v:Virologist":
Deactivate "n:NukleicAcid"
"v:Virologist" --> Player
Deactivate "v:Virologist"

@enduml