@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Collect Bag

actor Player

Player -> "virologist: Virologist": collect()
Activate "virologist: Virologist"

"virologist: Virologist" -> "shelter:Shelter": getCollectable()
Activate "shelter:Shelter"
"shelter:Shelter" --> "virologist: Virologist": <Bag>
Deactivate "shelter:Shelter"

"virologist: Virologist" -> "bag: Bag": collectBy(Virologist)
Activate "bag: Bag"


"bag: Bag" -> "bag: Bag"++ : applyEffect(virologist)

'Itt miért kéri le magától a méretét?
"bag: Bag" -> "bag: Bag"++ : getExtraInventorSize()
"bag: Bag" --> "bag: Bag"-- : extraInventorSize

"bag: Bag" -> "virologist: Virologist"++ : getInventorSize()
"virologist: Virologist" --> "bag: Bag"-- : inventorSize

"bag: Bag" -> "virologist: Virologist"++ : setInventorySize(inventorSize + extraInventorSize)
"virologist: Virologist" --> "bag: Bag"--

"bag: Bag" --> "bag: Bag"--:

"bag: Bag" --> "virologist: Virologist"--


Deactivate "bag: Bag"



"virologist: Virologist" --> Player
Deactivate "virologist: Virologist"

@enduml