@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Collect NucleicAcid

actor Player

Player -> "v:Virologist": collect()
Activate "v:Virologist"

"v:Virologist" -> "s:Storage": getCollectable()
Activate "s:Storage"
"s:Storage" -> "v:Virologist": <NucleicAcid>
'Ide sztem Matter illene jobban, csak hát az absztrakt...
Deactivate "s:Storage"

"v:Virologist" -> "n:NucleicAcid": collectBy(Virologist)
Activate "n:NucleicAcid"

"n:NucleicAcid" -> "v:Virologist" ++: SetNucleicAcid()
"v:Virologist"--> "n:NucleicAcid" --

"n:NucleicAcid" --> "v:Virologist":
Deactivate "n:NucleicAcid"
"v:Virologist" --> Player
Deactivate "v:Virologist"

@enduml