@startuml
'https://plantuml.com/sequence-diagram

autonumber

Mainframe Drop Gloves

actor Player
Player->"virologist: Virologist"++:discard(virologist, gloves)
"virologist: Virologist"->"cloak: Cloak"++:discard()
                   "cloak: Cloak" -> "cloak: Cloak"++ : removeEffect(targetVirologist)
                    note over  "virologist: Virologist", "cloak: Cloak"
                    Reset the protection strategy to **virologists default**
                     end note

                    "cloak: Cloak" ->  "virologist: Virologist"++: setProtectionStrategy()
                    "virologist: Virologist" --> "cloak: Cloak"--

                    "cloak: Cloak"-->  "cloak: Cloak"--

                         "cloak: Cloak"--> "virologist: Virologist"--
"virologist: Virologist"-->Player--
@enduml