@startuml
'https://plantuml.com/sequence-diagram

autonumber

Mainframe Drop Cloak

actor Player
Player->"virologist: Virologist"++:discard(virologist, cloak)
"targetVirologist: Virologist"->"cloak: Cloak"++:discard()
                   "cloak: Cloak" -> "cloak: Cloak"++ : removeEffect(targetVirologist)
                    note over  "targetVirologist: Virologist", "cloak: Cloak"
                    Reset the protection strategy to **virologists default**
                     end note

                    "cloak: Cloak" ->  "targetVirologist: Virologist"++: setProtectionStrategy()
                    "targetVirologist: Virologist" --> "cloak: Cloak"--

                    "cloak: Cloak"-->  "cloak: Cloak"--

                         "cloak: Cloak"--> "targetVirologist: Virologist"--
"virologist: Virologist"-->Player--
@enduml