@startuml
'https://plantuml.com/sequence-diagram

autonumber
Mainframe Drop NucleicAcid

actor Player
Player -> "v:Virologist" ++: discard(v, n)
"v:Virologist"->"n:NucleicAcid"++:discard(Virologist)
 note over  "n:NucleicAcid"
                    the player chose the wanted amount
                     end note
"n:NucleicAcid"->"v:Virologist":SetNucliecAcid(amount:int)
activate "v:Virologist"
"v:Virologist"-->"n:NucleicAcid"
deactivate "v:Virologist"
"n:NucleicAcid"-->"v:Virologist"--
"v:Virologist" --> Player
Deactivate "v:Virologist"
@enduml