@startuml
'https://plantuml.com/sequence-diagram

autonumber
Mainframe Drop AminoAcid
actor Player
Player -> "v:Virologist": discard(v,a)
"v:Virologist"->"a:AminoAcid"++:discard(v:Virologist)
                    note over  "a:AminoAcid"
                    the player chose the wanted amount
                     end note
"a:AminoAcid"->"v:Virologist":SetAminoAcid(amount:int)
activate "v:Virologist"
"v:Virologist"-->"a:AminoAcid"
deactivate "v:Virologist"
"a:AminoAcid"-->"v:Virologist"--
"v:Virologist"-->Player

@enduml