@startuml
'https://plantuml.com/sequence-diagram

autonumber

Mainframe Drop Bag

actor Player
Player->"virologist: Virologist"++:discard(virologist, bag)
"virologist: Virologist"->"bag: Bag"++:discard()

         "bag: Bag" -> "bag: Bag"++ : removeEffect(targetVirologist)

                 "bag: Bag" -> "bag: Bag" ++ : getExtraInventorSize()
                 "bag: Bag"  --> "bag: Bag" -- : extraInventorSize

                 "bag: Bag"  -> "virologist: Virologist"++ : getInventorSize()
                 "virologist: Virologist"--> "bag: Bag" -- : inventorSize

                 note over "virologist: Virologist", "bag: Bag"
                 **Decrease** the inventor size by the **bag's extra inventor size**
                 end note

                 "bag: Bag"  -> "virologist: Virologist"++ : setInventorySize(inventorSize - extraInventorSize)
                 "virologist: Virologist"--> "bag: Bag" --
                 "bag: Bag"--> "bag: Bag"--

        "bag: Bag"--> "virologist: Virologist"--
"virologist: Virologist"-->Player--
@enduml