@startuml
'https://plantuml.com/sequence-diagram

mainframe Protection Agent Remove

actor GameControl


GameControl->"virologist:Virologist"++: RefreshAgents()
    "virologist:Virologist"->"protection: Protection"++:decreaseTTL()
    "protection: Protection"-->"virologist:Virologist"--
    "virologist:Virologist"->"protection: Protection"++:removeEffect()

    note over "virologist:Virologist", "protection: Protection"
    Reset the protection strategy to **virologists default**
    end note

    "protection: Protection" -> "virologist:Virologist"++: setProtectionStrategy()
    "virologist:Virologist" --> "protection: Protection"--

"protection: Protection"-->"virologist:Virologist" --
"virologist:Virologist"-->GameControl--



@enduml

