@startuml
'https://plantuml.com/sequence-diagram
autonumber

mainframe Steal Cloak

actor Player

Player -> "robberVirologist: Virologist"++: steal(robberVirologist, targetVirologist)

"robberVirologist: Virologist" ->  "targetVirologist: Virologist"++: handleEquipmentSteal(robberVirologist, targetVirologist)


        note left  "targetVirologist: Virologist"
            The player choose the wanted thing here
        end note

         "targetVirologist: Virologist"->"cloak: Cloak"++:discard()

        "cloak: Cloak"--> "targetVirologist: Virologist"--
        "targetVirologist: Virologist" -> "cloak: Cloak"++ : removeEffect(targetVirologist)
        note over  "targetVirologist: Virologist", "cloak: Cloak"
        Reset the protection strategy to **virologists default**
        end note
        
        "cloak: Cloak" ->  "targetVirologist: Virologist"++: setProtectionStrategy()
         "targetVirologist: Virologist" --> "cloak: Cloak"--

        "cloak: Cloak"--> "targetVirologist: Virologist"--

     "targetVirologist: Virologist" -->"robberVirologist: Virologist"--: cloak
    "robberVirologist: Virologist"->"cloak: Cloak"++:collectby(robberVirologist)
    "cloak: Cloak" --> "robberVirologist: Virologist"--
"robberVirologist: Virologist" -> "cloak: Cloak"++ : applyEffect(robberVirologist)



"cloak: Cloak" -> "cloak: Cloak"++ : getStrategy()
"cloak: Cloak" --> "cloak: Cloak"-- : defenseStrategy

"cloak: Cloak" -> "robberVirologist: Virologist"++: setDefenseStrategy(defenseStrategy)
"robberVirologist: Virologist" --> "cloak: Cloak"--
"cloak: Cloak" --> "robberVirologist: Virologist"--


"robberVirologist: Virologist" --> Player --
@enduml