@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Virologist paralyzed move

actor Player

Player -> Virologist: move(direction)
Activate Virologist

note right of Virologist
Get a random integer as direction
end note
Virologist -> Virologist: randomDirection = generateRandomNumber()

Virologist -> FieldCurrent: getNeighbor(randomDirection)
Activate FieldCurrent
FieldCurrent --> Virologist: targetField : Field
Deactivate FieldCurrent

Virologist -> FieldCurrent: removeVirologist(this)
Activate FieldCurrent
FieldCurrent --> Virologist:
Deactivate FieldCurrent

Virologist -> targetField: acceptVirologist(this)
Activate targetField
targetField --> Virologist:
Deactivate targetField
Virologist --> Player:

Deactivate Virologist
@enduml