@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Virologist default defense stategy


Virologist -> TargetVirologist++: attack(Agent, Virologist, TargetVirologist)

TargetVirologist -> TargetVirologist++: defense(Agent, Virologist, TargetVirologist)


note over TargetVirologist
    When the virologist have a cloak, there is
    an **82.3%** chance that the attack will **fail.**
end note

note right of TargetVirologist
Get a random number as a percentage.
end note

TargetVirologist -> TargetVirologist: surviveRate = generateRandomNumber()

opt if (surviveRate > 0.823)
    TargetVirologist -> Agent++: +applyEffect(TargetVirologist)
    Agent --> TargetVirologist--
end opt


TargetVirologist --> TargetVirologist--

TargetVirologist --> Virologist --
@enduml