@startuml
'https://plantuml.com/sequence-diagram
mainframe Virologist wear gloves when step on Cursed Lab


participant "cursedland:CursedLab" as CursedLab
participant "v: Virologist" as Virologist
participant "glovesStrategy: defenseStrategy" as defenseStrategy
participant "glovesOnVirologist:Gloves" as Gloves

CursedLab->Virologist++:attack(bearDance:Agent, attackerVirologist:Virologist)
Virologist->defenseStrategy++:defense(bearDance:Agent,v:Virologist, null)
defenseStrategy->Gloves++:getLife()
Gloves-->defenseStrategy--:life:int

note right of defenseStrategy
Because the attackerVirologist parameter is "null" in attack(),
won't be a counter attack
end note

defenseStrategy->Gloves++:decreaseTTL()
Gloves-->defenseStrategy--
defenseStrategy->Gloves++:getLife()
Gloves-->defenseStrategy--:life int
opt life==0
defenseStrategy->Gloves++:discard(v:Virologist)
Gloves-->defenseStrategy--
end opt
defenseStrategy-->Virologist--
Virologist-->CursedLab--

@enduml