@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Virologist kills with axe

actor Player
participant "v: Virologist" as Virologist
participant "axemurder: murderStrategy" as axe
participant "currentField: Field" as currentField
participant "targetVirologist:Virologist" as targetVirologist


Player->Virologist++:murder(targetVirologist:Virologist)
Virologist->axe++:murder(targetVirologist:Virologist)
axe->axe++:getLive()
axe-->axe--:live:int
opt live==1
axe->Virologist++:getField()
Virologist-->axe--:field:Field
axe->targetVirologist++:getField()
targetVirologist-->axe--:field2:Field
opt field equals field2
    axe->targetVirologist++:die()
    targetVirologist-->axe--
    destroy targetVirologist
end opt
axe->axe++:decreaseTTL()
axe-->axe--
end opt
axe-->Virologist--
Virologist-->Player--
@enduml