@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Player
Player->"vc: VirologistController"++: stealEventListener(e: Event)
"vc: VirologistController"->"v:Virologist"++: getRoundRunStrategy()

"v:Virologist"-->"vc: VirologistController"--: rrs
"vc: VirologistController"->"rrs:RoundRunStrategy"++: steal(coll: Collectable, targetVirologist: Virologist)
"rrs:RoundRunStrategy"-->"vc: VirologistController"--

"vc: VirologistController"->"vw:VirologistView"++: renderActionMenu()

"vw:VirologistView"-->"vc: VirologistController"--
"vc: VirologistController"-->Player--
@enduml