@startuml

interface Steppable{
    'Invoked at the start of the next Round eg. reduce the Agent's lifetime
    +nextRound(): void
}

interface Collectable{
    +collectBy(v: Virologist): void
}

class Field{
 +getNeighbors(): Array<Field>
 +getNeighbor(direction: Integer): Field
 +addNeighbor(neighbor: Field): void
 +acceptVirologist(virologist: Virologist): void
 +removeVirologist(virologist: Virologist): void
}

class Lab{
    +getGencode(): Gencode
}
class Storage{
    +getAminoAcid(amount: Integer): AminoAcid
    +getNucleicAcid(amount: Integer): NucleicAcid
}
class Shelter{
    +getEquipmentCount(): Integer
    +getEquipment(): Equipment
}

class Virologist {
    +move(direction: Integer): void
    +collect(field: Field): Collectable
    +useAgent(agent: Agent, attacker: Virologist, defender: Virologist): void
    +stealEquipment(robber: Virologist): Equipment
    +stealMatter(matter: Matter): Matter
    +canTouch(robber: Virologist): boolean
    +nextRound(): void
}

abstract class Matter {

}

class AminoAcid
class NucleicAcid

abstract class Equipment {
    +collectBy(v: Virologist)
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}

class Cloak{
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}

class Gloves{
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}

class Bag{
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}

abstract class Agent{
    gencode: Gencode
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
    +nextRound(): void
}

class Virus{
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}
class Vacine{
    +applyEffect(v: Virologist)
    +removeEffect(v: Virologist)
}

'This Gencode is basically the crafting receipt of the Agent
class Gencode {
    +requiredNucleicAcid: NucleicAcid
    +requiredAminoAcid: AminoAcid
    +collectBy(v: Virologist): void
}

Field <|-- Lab
Field <|-- Storage
Field <|-- Shelter

Lab o-- Gencode
Storage o-- Equipment

Virologist --o Field
Virologist *-d- Matter
Virologist *-d- Equipment
Virologist <|-l Steppable

Matter <|-- AminoAcid
Matter <|-- NucleicAcid

Equipment <|-- Cloak
Equipment <|-- Gloves
Equipment <|-- Bag

Agent <|- Steppable
Agent <|-- Virus
Agent <|-- Vacine

Collectable<|- Gencode
Collectable <|-l Equipment


@enduml