@startuml
'https://plantuml.com/class-diagram


note top of MapController{
    **initEventListener** acts as an event listener
}

class GameController {
    +initGame()
}

class MapView {
    -renderFields(): void
    -renderConnections(): void
}
class MapController {
    +initEventListener(Event e)

}

GameController <.- MapController

MapController *- MapView

@enduml