@startuml
'https://plantuml.com/sequence-diagram

autonumber

'actor Player
mainframe nextTurn

'kell ez???

loop while someone not won
    loop all virologists
        GameControler -> Virologist: startOfTurn()
        activate Virologist
            'Do the turn, make all stuff happen
        Virologist -> GameControler
        deactivate Virologist
    end
end


@enduml