@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Virologist paralyzed round

actor GameControl
GameControl -> Virologist: RoundRun()
note left of Virologist
User input does not have an effect
end note
Activate Virologist
Virologist->GameControl:reportGenCode()
Activate GameControl


GameControl-->Virologist
deactivate GameControl


Virologist->Virologist: RefreshAgents()
Activate Virologist
Virologist-->Virologist
deactivate Virologist


Virologist-->GameControl
Deactivate Virologist

@enduml