@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Virologist default round

actor GameControl
GameControl -> Virologist: RoundRun()
Activate Virologist
loop while userinput!=EndOfTurn
    actor Player
    opt userinput=move
        Player->Virologist:move()
        Activate Virologist
        Virologist-->Player
        Deactivate Virologist
    end
    opt userinput=useAgent
        Player->Virologist:useAgent()
        Activate Virologist
        Virologist-->Player
        Deactivate Virologist
    end
end
Virologist->GameControl:reportGenCode()
Activate GameControl

GameControl->Virologist: RefreshAgents()
Activate Virologist
Virologist-->GameControl
deactivate Virologist
GameControl-->Virologist
deactivate GameControl
Virologist-->GameControl
Deactivate Virologist

@enduml