@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe Create Agent

actor Player

Player -> Virologist: createAgent(Gencode)
Activate Virologist

Virologist -> Gencode: getRequiredNucleicAcid()
Activate Gencode
Gencode --> Virologist: requiredNucleicAcid
Deactivate Gencode

Virologist -> Gencode: getRequiredAminoAcid()
Activate Gencode
Gencode --> Virologist: requiredAminoAcid
Deactivate Gencode

opt Virologist.getAminoAcid() > requiredAminoAcid && Virologist.getNucleicAcid() > requiredNucleicAcid
    Virologist -> Virologist: aminoAcid -= requiredAminoAcid
    Virologist -> Virologist: nucleicAcid -= requiredNucleicAcid
end

Virologist -> Agent **
Agent --> Virologist

Virologist -> Virologist: storeAgent(Agent)
'Ide szerintem lifelineokat be kéne rajzolni (Meg a fentiekbe is)

Virologist --> Player
Deactivate Virologist

@enduml