@startuml
'https://plantuml.com/sequence-diagram

mainframe Refresh Agents

actor GameControl


GameControl->Virologist: RefreshAgents()
Activate Virologist
    loop all Agent on Virologist
            Virologist->Agent:decreaseTTL()
            Activate Agent
                opt lifeofanagent=0
                    'TODO: A removeEffect() függvényt az ágensen kell meghívni, és nem a virológuson
                    'TODO: A lifeline-oknak legyen rendesen vége és eleje. Ne legyen egybe az egész
                    Virologist->Agent:removeEffect()
                    Activate Agent
                    Agent-->Virologist
                    Deactivate Agent
                end
            Agent-->Virologist: b

            'biztos kell nekünk ez a rész?
            opt b=false
            Virologist->Agent:destroy()
            Activate Agent
            Agent-->Virologist
            Deactivate Agent
            Destroy Agent
            end
            Deactivate Agent
    end

Virologist-->GameControl
deactivate Virologist


@enduml

