@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

Player -> Virologist: collect()
Activate Virologist
Virologist --> Player: collectable

Deactivate Virologist
Player -> collectable: collectBy(Virologist)
Activate collectable

collectable --> Player:
Deactivate collectable

@enduml