@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

Player -> Virologist: discard(Collectable)
Activate Virologist
Virologist -> Collectable: destroy()
Activate Collectable
Collectable --> Virologist:
Destroy Collectable

Virologist --> Player:
Deactivate Virologist
@enduml