@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor GameControl
GameControl -> Virologist: RoundRun()
Activate Virologist
loop while userinput!=EndOfTurn
    actor Player
    opt userinput=move
        Player->Virologist:move()
        Activate Virologist
        Virologist-->Player
        Deactivate Virologist
    end
    opt userinput=useAgent
        Player->Virologist:useAgent()
        Activate Virologist
        Virologist-->Player
        Deactivate Virologist
    end
end
Virologist->GameControl:reportGenCode()
Activate GameControl
GameControl-->Virologist
deactivate GameControl
Virologist-->GameControl
Deactivate Virologist

@enduml