@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor GameControl


        GameControl -> Virologist: nextRound()
        Activate Virologist
        loop while userinput!=EndOfTurn

        end

        Virologist-->GameControl
        Deactivate Virologist


@enduml