@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

Player -> TargetVirologist: stealMatter(Virologist, matter)
Activate TargetVirologist



TargetVirologist --> Player: matter
Deactivate TargetVirologist

@enduml