@startuml


GameControler -> Virologist: startOfTurn()
activate Virologist

Virologist -> Virologist: this.roundRunStrategy.roundRun()
activate Virologist
deactivate Virologist

Virologist -> GameControler
deactivate Virologist


@enduml