@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

Player -> Virologist: useAgent(Agent, TargetVirologist)
Activate Virologist

Virologist -> TargetVirologist: canTouch(Virologist)
Activate TargetVirologist
TargetVirologist --> Virologist: canBeTouched
Deactivate TargetVirologist
opt canBeTouched

Virologist -> Agent: applyEffect(TargetVirologist)
Activate Agent

Agent -> TargetVirologist: effectApplied()
Activate TargetVirologist

TargetVirologist --> Agent:
Deactivate TargetVirologist
Agent --> Virologist
Deactivate Agent
end


Virologist --> Player:
Deactivate Virologist
@enduml