@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

Player -> Virologist: useAgent(Agent, TargetVirologist)
Activate Virologist

Virologist -> Agent: applyEffect(TargetVirologist)
Activate Agent

Agent -> TargetVirologist: effectApplied()
Activate TargetVirologist
'TODO it's probably not totally completed yet
TargetVirologist --> Agent: 
Deactivate TargetVirologist
Agent --> Virologist
Deactivate Agent

Virologist --> Player:
Deactivate Virologist
@enduml